image: docker:stable-git

variables:
  GIT_DEPTH: '50'
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: 'recursive'
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:stable-dind

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME-$CI_COMMIT_TAG"

Release:
  stage: build
  timeout: 3h
  only:
    refs:
      - '12.0'
  except:
    refs: ['/^hotfix\/.*$/', 'schedules']
  before_script:
  - export $(egrep -v '^#' .env | xargs)
  script:
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  - image="${IMAGE}:${CI_COMMIT_TAG}${CI_COMMIT_REF_NAME}"
  - fromimage="${FROM}:${FROM_VERSION}"

  - docker pull ${fromimage} &> /dev/null

  - docker build --tag "${image}-${CI_PIPELINE_IID}" --build-arg FROM_IMAGE="${fromimage}" .
  - docker push "${image}-${CI_PIPELINE_IID}" &> /dev/null
  - echo "${image}-${CI_PIPELINE_IID}"
  tags:
    - erp