version: '3.4'

services:
  erp:
    tty: true
    image: "${IMAGE}:${ODOO_VERSION}-dev"
    container_name: erp
    # command: ['--dev', 'reload'] # Disable for Mac OS with M1 chip
    depends_on:
      - db
      - wdb
    ports:
      - "8069:8069"
      - "8072:8072"
      - "5555:5555"
    volumes:
      - web-data:/var/lib/odoo
      - ./src:/mnt/src-addons/src
      - ./vendor:/mnt/vendor-addons
      # - ./vendor/odoo/ce/addons:/var/lib/odoo/addons/12.0
      # - ./vendor/odoo/ce/odoo/addons:/usr/lib/python3/dist-packages/odoo/addons
    environment:
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - PROXY_MODE=True
      - LIMIT_TIME_CPU=5600
      - LIMIT_TIME_REAL=7200
      - WORKERS=0
      - WDB_SOCKET_SERVER=wdb
      - WDB_SOCKET_PORT=19840
      - WDB_WEB_SERVER=localhost:1984
    networks:
      - webapp

  db:
    image: postgres:12
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - webapp

  wdb:
    image: shepilovvladislav/wdb
    container_name: wdb
    ports: ['1984:1984']
    networks:
      - webapp

volumes:
  web-data:
  db-data:

networks:
    webapp:
        driver: bridge
