version: '3.4'

services:
  erp:
    tty: true
    image: "${IMAGE}:${ODOO_VERSION}-dev"
    container_name: erp
    command: ['--dev', 'reload']
    depends_on:
      - db
      - wdb
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - web-data:/var/lib/odoo
      - ./src:/mnt/src-addons/src
      - ./vendor:/mnt/vendor-addons
      - ./vendor/odoo/ce/addons:/var/lib/odoo/addons/13.0
      - ./vendor/odoo/ce/odoo/addons:/usr/lib/python3/dist-packages/odoo/addons
    environment:
      - DB_HOST=db
      - DB_USER=gangala
      - DB_PASSWORD=M7LEA7chfE9
      - ERP_PROXY_MODE=True
      - ERP_LIMIT_TIME_CPU=5600
      - ERP_LIMIT_TIME_REAL=7200
      - ERP_WORKERS=0
      - WDB_SOCKET_SERVER=wdb
      - WDB_SOCKET_PORT=19840
      - WDB_WEB_SERVER=localhost:1984
    networks:
      - webapp

  db:
    image: postgres:12
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=M7LEA7chfE9
      - POSTGRES_USER=gangala
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - webapp

  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']
    networks:
      - webapp

volumes:
  web-data:
  db-data:

networks:
    webapp:
        driver: bridge
